spring:
  data:
    cassandra:
       keyspace-name: main
       username: NktuMnJhoYeZXQhRYFtZbZKa
       password: Roz4pKRQRHvEjragsa+.gbjhewmclDWK83cC9ZK0JAQ2,-CquN3k8aX-+,m8iTLcTwMgfLzYLJ-hZdWN2QRQ144yxKW_vmzJHT7ptPMjyh9NinTD4Qly-fq0edzo6bqK
       schema-action: create-if-not-exists
       requests:
        timeout: 30s
       connection:
        connect-timeout: 30s
        init-query-timeout: 30s

datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra.db:
  id: a3a403bd-a99b-4437-b374-912e10710b1d
  region: us-west1
  keyspace: main
  application.token: AstraCS:NktuMnJhoYeZXQhRYFtZbZKa:7cb57ba25ac2d677bb444842b19d13e47311901d3f2176a20941e0695f5e9fb5