spring:
  data:
    cassandra:
       keyspace-name: main
       username: <username>
       password: <password>
       schema-action: create-if-not-exists
       requests:
        timeout: 30s
       connection:
        connect-timeout: 30s
        init-query-timeout: 30s

datastax.astra:
  secure-connect-bundle: secure-connect.zip
datastax-java-driver:
  basic:
    request:
      timeout: 15s

astra.db:
  id: <db-id>
  region: us-west1
  keyspace: main
  application.token: <token>